apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    demo: helm
spec:
# helm goes into values.yaml and replaces the values with the values in values.yaml
  replicas: {{ .Values.deployment.replicas }}
  # replicas: 3 
  selector:
    matchLabels:
      app: nginx
      demo: helm
  template:
    metadata:
      labels:
        app: nginx
        demo: helm
    spec:
      containers:
      - name: nginx
        # if number no need of double quotes if string need double quotes
        image: "nginx:{{ .Values.deployment.imageVersion }}"
        # image: nginx
        ports:
        - containerPort: 80
